### ISSUE TITLE
Add SeaMonkey support

### ISSUE THREAD

**Issue by ghost** [janodvarko/ccdump#1]
I've checked, that this addon is working with SeaMonkey, can you add official support for it? Appropriate section for install.rdf:
    &lt;!-- SeaMonkey --&gt;
    &lt;em:targetApplication&gt;
      &lt;Description&gt;
        &lt;em:id&gt;{92650c4d-4b8e-4d2a-b7eb-24ecf4f6b63a}&lt;/em:id&gt;
        &lt;em:minVersion&gt;2.10a1&lt;/em:minVersion&gt;
        &lt;em:maxVersion&gt;2.10a1&lt;/em:maxVersion&gt;
      &lt;/Description&gt;
    &lt;/em:targetApplication&gt;

**Comment by janodvarko** [comment]
Great, thanks for testing!

install.rdf modified here:
https://github.com/janodvarko/ccdump/commit/baaade2a0bf22c8c6b74416d82ebc9727210c018

Will be in v0.3

Honza
